language: python
python:
    - '3.6'
    - '3.7'
dist: xenial
sudo: true
before_install:
    - sudo apt-get install -y gfortran
install:
    - pip install -r requirements.txt pycodestyle
script:
    - pycodestyle tom_* --exclude=*/migrations/* --max-line-length=120
    - python3 manage.py test
