name: Release to PyPi

on:
  release:
    types: [published]

jobs:
  publish_to_pypi:
    runs-on: ubuntu-latest
    environment: release  # configured in repo Settings/Environments; referenced in PyPI OIDC
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # numpy is a problem with 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry config virtualenvs.create false  # tell poetry not to create a new virtual environment
        poetry self add "poetry-dynamic-versioning[plugin]"
    - name: Build package with poetry
      run: |
        poetry build -f wheel
        poetry build -f sdist
    - name: Publish to PyPI with pypi-publish (trusted publishing)
      uses: pypa/gh-action-pypi-publish@v1.8.5
